version: 2.1

workflows:
  deploy snapshot:
    jobs:
      - build:
          context:
          - Test My Org

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - run: 
          name: import GPG key
          command: echo -e "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes
      - run: 
          name: list files
          command: |
            ls -la
            ls -la ~/.circleci
      - run: 
          name: deploy to snapshot repository
          command: mvn clean deploy -T 1C -P sonatype  --settings ./.circleci/settings.xml
