version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
          - Test My Org

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: 
          name: import GPG key
          command: echo -e "$GPG_KEY" | base64 -d 
      # - checkout
      # - run: mvn clean deploy -T 1C -P sonatype

    
