version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run: echo -e ${env.GPG_KEY} | gpg --import
      - run: mvn clean deploy -T 1C -P sonatype
