version: 2.1

orbs:
  maven: circleci/maven@1.2.0

paramters:
  settings_file: .circleci/settings.xml


workflows:
  maven_test:
    jobs:
      - maven/parallel_test:
            parallelism: 4
            # filters:
            #   branches:
            #     only:
            #       - main
