version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - run: 
          name: import GPG key
          command: echo -e "$GPG_KEY" | base64 -d | gpg --import        
      # - checkout
      # - run: mvn clean deploy -T 1C -P sonatype
