version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
          - Test My Org

jobs:
  build:
    docker:
      - image: cimg/alpine
    steps:
      - run: 
          name: import GPG key
          command: echo -e "$GPG_KEY" | gpg --import
      # - checkout
      # - run: mvn clean deploy -T 1C -P sonatype

    
