version: 2.1

orbs:
  maven: circleci/maven@1.2.0


workflows:
  maven_test:
    jobs:
      - maven/test:
            parallelism: 4
            settings_file: .circleci/settings.xml
            # filters:
            #   branches:
            #     only:
            #       - main
